include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/generated_plugin_registrant.dart"

linter:
  rules:
    public_member_api_docs: false
    avoid_print: true
    sort_pub_dependencies: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
